# Generated by Django 3.0.6 on 2020-05-21 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockpavingimage',
            old_name='images',
            new_name='b_images',
        ),
    ]
