# Generated by Django 3.0.6 on 2020-05-24 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200522_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Walls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_title', models.CharField(max_length=50)),
                ('w_pic', models.IntegerField()),
                ('w_label', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Wallsimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_images', models.FileField(upload_to='images/')),
                ('wall', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.Walls')),
            ],
        ),
    ]
