# Generated by Django 3.0.6 on 2020-05-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_walls_wallsimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlebio', models.CharField(max_length=100)),
                ('aboutimg', models.ImageField(upload_to='')),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('overview', models.TextField()),
            ],
        ),
    ]
